---
title: "Dashboard1"
author: "ssallem"
date: '2022-04-19'
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
  pdf_document: default
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
library(highcharter)
library(dplyr)
library(viridisLite)
library(forecast)
library(treemap)
library(flexdashboard)
library(viridis)

thm <- 
hc_theme(
  colors = c("#1a6ecc", "#434348", "#90ed7d"),
  chart = list(
    backgroundColor = "transparent",
    style = list(fontFamily = "Source Sans Pro")
  ),
  xAxis = list(
    gridLineWidth = 1
  )
)

```



## Column {data-width="600"}

### 판매 예측

```{r}
AirPassengers %>% 
forecast(level = 90) %>% 
hchart() %>% 
hc_add_theme(thm)
```

### 지역별 판매량

```{r}
data("USArrests", package = "datasets")
data("usgeojson")

USArrests <- USArrests %>%
  mutate(state = rownames(.))

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list_parse2()

highchart() %>%
  hc_add_series_map(usgeojson, USArrests, name = "Sales",
                    value = "Murder", joinBy = c("woename", "state"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
```